using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace Phone_Contacts.Models
{
    public class Contact
    {
        //Generated by EF Core
        public int ContactId { get; set; }

        [Required(ErrorMessage = "Please enter a name.")]
        [StringLength(50, ErrorMessage = "Name cannot exceed 50 characters.")]
        public string Name { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please enter a phone number.")]
        [RegularExpression(@"^\d{3}-\d{3}-\d{4}$", ErrorMessage = "Phone number must be in the format 555-123-4567.")]
        public string? Number { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please enter a street address.")]
        [StringLength(100)]
        public string Street { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please enter a city.")]
        [StringLength(50)]
        public string City { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please enter a state.")]
        [StringLength(2, ErrorMessage = "Use the 2-letter state abbreviation.")]
        public string State { get; set; } = string.Empty;

        [Required(ErrorMessage = "Please enter a ZIP code.")]
        [StringLength(5, ErrorMessage = "Enter a valid ZIP code.")]
        public string Zip { get; set; } = string.Empty;

        //[Required(ErrorMessage = "Please enter an address.")]
        //[StringLength(200, ErrorMessage = "Address cannot exceed 200 characters.")]
        //public string Address { get; set; } = string.Empty;

        [StringLength(100, ErrorMessage = "Note cannot exceed 100 characters.")]
        public string? Note { get; set; }


    }
}
